### PR TITLE
Start translation of help tekst

### PR DESCRIPTION
**Pull request by francoisduprez**
I started to translate the help tekst. But it would be nice if it could be re-readed by someone with more knowledge of brewing theory. :)

### CODE REVIEW

**Comment by Rasinari** [comment]
If you have problems in understandig issues you can ask me. I'm the author of original  Tooltips.

**Comment by francoisduprez** [comment]
> If you have problems in understandig issues you can ask me. I'm the author of original Tooltips.
That's realy nice. My biggest problem is the translation of technical terms from German to Dutch. Like Grünschlauchen. This are words i don't know, and can't find logical links. That's a problem of me and missing theory of brewing on my side.

**Comment by Rasinari** [comment]
OK – these problems are obvious. We can solve this.  
"Green hosing is the hosing of the not yet completely finished fermented green beer at the end of the main fermentation. One hoses x°P above the residual extract, which was previously determined with the final degree of fermentation.
The young beer then has green-hose maturity."

**Comment by Rasinari** [comment]
Maybe [url="https://www.deepl.com/translator"]DeepL[/url] will be helpful. There is a good algorithm translating Germand-Dutch…

**Comment by francoisduprez** [comment]
> Maybe https://www.deepl.com/translator will be helpful. There is a good algorithm translating German-Dutch…

Sorry for the late reply, bussy with work.. For the biggest part of the translation i use deepl.com. Because it's easier to copy, read, correct and copy, paste back.. Butt the special terms are most of the time not translated or translated literally. green-hose maturity is in Ducht "groene slang rijpheid. " I understand your explanation, but now i have to find the right dutch sentence or word.. :)

**Pull request merged**
