### PR TITLE
Dutch Translation

### PR DESCRIPTION
**Pull request by francoisduprez**
Translated a lot of help text and the new parts. Not completely finished, but almost.

### CODE REVIEW

**Comment by francoisduprez** [comment]
Also changed the Webview files and made the translation more Dutch. Stil some big parts of the help balloons in recept have to be done. But all the text is done.

**Comment by Rasinari** [comment]
> Also changed the Webview files and made the translation more Dutch. Stil some big parts of the help balloons in recept have to be done. But all the text is done.

Really really great. If there are any ambiguities in German technical terms, please feel free to ask me.

**Comment by francoisduprez** [comment]
> > Also changed the Webview files and made the translation more Dutch. Stil some big parts of the help balloons in recept have to be done. But all the text is done.
> 
> Really really great. If there are any ambiguities in German technical terms, please feel free to ask me.

I learned that a lot of German term can not be translated to Dutch and a lot of terms don't need to be translated because the mean almost the same.  
Like First Wort Hop, High Gravity Brewing are useless to translate in Dutch  en Anstellen der Hefe = Aanstellen van de Gist is almost the same in Dutch.

But i have some problems with the hop.

German                              Translation

Vorderwürze                       First Wort Hop
Ausschlagen                       Hopstand

(Tabblad Recept)
Nachisomerisierungszeit     Hopstand (Dutch is also Na-isomerisatietijd) 

But i never cam across this term, so i don't know how to translate... Or maybe i don't need to translate it..

Same problem with "Speisemenge" Dutch is "hoeveelheid Voedsel" (Voedselhoeveelheid) Voedsel=Food. I know what it is and how it's works and i also ask in a few dutch bierforums but they have the same problem. They know what it is and how it works, but no ranslation.  I think i't something realy German.. :) So there is no real Dutch translation for it.  Vers Wort, Onvergist Wort.. 

But if a come across some difficulties is will ask..

**Comment by francoisduprez** [comment]
Ausschlagen = Draining the finished wort. 
This one i don't understand in combination with cooking and the Hop. Do you put in the hop, when the wort is cooled down and ready to put in the fermentation container?  Or do you put in the hop when you are cooling down?

Vorderwürze = Hopping BEFORE hop cooking, after lautering.
Ok, this one i understand. Sadly there is no real Dutch translation for. I keep it as First Wort Hopping

Nachisomerisierungzeit = Time between flame out and 80°C; time with active hop bitterness after end of boil.
Ah, i think i get this one. So i turn off the power and the time it needs to get to 80°C is the "Nachisomerisierungzeit"
Or, if the wort cooled down. It's the time at 80°C?
But i think i will translate it with " Na-isomerisatietijd" 

Speisemenge = Quantity of young beer
This one is easy, but there is no word for it in Dutch. And with young beer, i think at the wort with yeast put in. Fresh Wort or Unfermented Wort sounded more logical for me..

The problem with me and a lot of the translations, is that i'm a starting hobby brewer. Only brewed maybe 10/15 times. So many technical terms are new for me. And the German i know, i learned myself on holiday and television.. 

So bear with me...

**Pull request merged**
