### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by dystechnic**

### CODE REVIEW

**Comment by Rasinari** [comment]
Is it also possible to translate the ToolTips into Dutch?

**Comment by dystechnic** [comment]
> Is it also possible to translate the ToolTips into Dutch?

Yes, that will be done in time.

**Comment by BourgeoisLab** [comment]
You removed the file extention from "kbh_nl.ts". Your file is called "kbh_nl". You should correct that.

**Comment by BourgeoisLab** [comment]
I renamed the file and did a lupdate. I think it is ready for merge now.

**Comment by dystechnic** [comment]
> You removed the file extention from "kbh_nl.ts". Your file is called "kbh_nl". You should correct that.

Oops,sorry.

**Pull request merged**
